---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Link the dotfile"
  ansible.builtin.file:
    src: "{{ item.source | mandatory }}/{{ item.file }}"
    dest: "{{ item.dest | mandatory }}/{{ item.file }}"
    owner: "{{ user.username | mandatory }}"
    group: "{{ user.group | default(user.username) }}"
    force: true
    follow: false
    state: "link"
