---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Clone the repository: {{ item.repo | mandatory }}"
  ansible.builtin.git:
    repo: "{{ item.repo | mandatory }}"
    dest: "{{ item.dest | mandatory }}"
    version: "{{ item.version | default('HEAD') }}"
    accept_hostkey: true
    key_file: "{{ item.key | default(omit) }}"
  register: "clone_result"

- name: "Set the repository permissions: {{ item.repo | mandatory }}"
  ansible.builtin.file:
    dest: "{{ item.dest | mandatory }}"
    owner: "{{ user.username | mandatory }}"
    group: "{{ user.group | default(user.username) }}"
    recurse: true
  # noqa no-handler
  when: "clone_result is changed"
