---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Clone the repository - {{ item.repo | mandatory }}"
  become: true
  become_user: "{{ user.username }}"
  ansible.builtin.git:
    repo: "{{ item.repo | mandatory }}"
    dest: "{{ item.dest | mandatory }}"
    version: "{{ item.version | default(omit) }}"
    accept_hostkey: true
    key_file: "{{ item.key | default(omit) }}"
  register: "clone_result"

- name: "Set the repository owner"
  ansible.builtin.file:
    dest: "{{ item.dest | mandatory }}"
    owner: "{{ user.username | mandatory }}"
    group: "{{ user.group | default(user.username) }}"
    recurse: true
  # noqa no-handler
  when: "clone_result is changed"
