---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Add the public key {{ item.name | mandatory }}"
  ansible.builtin.copy:
    dest: "{{ user_home }}/.ssh/{{ item.name }}.pub"
    content: "{{ lookup('ansible.builtin.file', item.public, lstrip=False, rstrip=False) }}"
    owner: "{{ user.username | mandatory }}"
    group: "{{ user.group | default(user.username) }}"
    mode: "u=rw,go=r"
  when:
  - "item.public is defined"

- name: "Add the private key {{ item.name | mandatory }}"
  ansible.builtin.copy:
    dest: "{{ user_home }}/.ssh/{{ item.name }}"
    content: "{{ lookup('ansible.builtin.file', item.private, lstrip=False, rstrip=False) }}"
    owner: "{{ user.username | mandatory }}"
    group: "{{ user.group | default(user.username) }}"
    mode: "u=rw,go="
  when:
  - "item.private is defined"
