---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Converge'
  hosts: 'all'
  become: true
  vars:
    users:
    - username: 'test1'
    - username: 'test2'
      state: 'absent'
    - username: 'test3'
      comment: 'Test User'
      password: 'secret'
    - username: 'test4'
      comment: 'Test User'
      forward: 'root@localhost'
    - username: 'test5'
      comment: 'Test User'
      authorized_keys:
      - key: 'molecule/default/keys/test-key.pub'
        state: 'absent'
    - username: 'test6'
      comment: 'Test User'
      private_keys:
      - name: 'test-key'
        public: 'molecule/default/keys/test-key.pub'
        private: 'molecule/default/keys/test-key'
    - username: 'fulldemo'
      comment: 'Demo User'
      password: 'really-secret-demo-password-1!'
      shell: '/bin/bash'
      append: true
      forward: 'demo@example.tld'
      authorized_keys:
      - key: 'molecule/default/keys/test-key.pub'
      private_keys:
      - name: 'test-key'
        public: 'molecule/default/keys/test-key.pub'
        private: 'molecule/default/keys/test-key'
      repositories:
      - repo: 'https://github.com/orennu/git-demo.git'
        dest: '/home/fulldemo/git-demo'
      dotfiles:
      - source: '/home/fulldemo/git-demo'
        dest: '/home/fulldemo'
        file: 'test-file.txt'

  pre_tasks:
  - name: 'Make sure we have git'
    ansible.builtin.package:
      name: 'git'
      state: 'present'
      update_cache: true

  roles:
  - role: 'mireiawen.users'
